version: "3"
services:
  flask-by-example:
    container_name: flask-by-example
    image: fongshway/flask-by-example:develop
    environment:
      - FLASK_APP=${FLASK_APP}
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/opt/app
    user: flask
    command: bash -c "flask run --host 0.0.0.0"
