version: '3'
services:

  app:
    container_name: flask_example
    hostname: flask_example
    environment:
      - FLASK_APP=example.py
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/opt/app
